#!/bin/bash

echo setupmongo time now: `date +"%T" `
until mongo --host peakabooMongo:27017 <<EOF
  var config = {
    "_id" : "peakaboo",
    "members": [{"_id": 0,
                 "host":"127.0.0.1"
               }]
  };
  rs.initiate(config, {force: true});
  rs.reconfig(config, {force: true});
EOF
do
  printf '.'
  sleep 1
done
