#!/bin/bash

if [ $MONGO_INIT == "true" ]
then
  echo "*** Trying to initialise oplog..."
  mongod --config /data/db/mongodb.conf &
  while ! mongo admin --eval "help()" >/dev/null 2>&1; do sleep 1; done
  mongo admin /data/db/replicaset.js
  sleep 5
else
  mongod --config /data/db/mongodb.conf
fi
