version: 2
jobs:
  build_and_push:
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            docker build -t "${CIRCLE_PROJECT_REPONAME}" .

      - run:
          name: Push images
          command: |
            only_on_branch=master
            if [ "${CIRCLE_BRANCH}" == "${only_on_branch}" ]; then
              if [ ! -z "${DOCKER_USER}" ] && [ ! -z "${DOCKER_PASS}" ]; then
                echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
                docker tag "${CIRCLE_PROJECT_REPONAME}" "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:sha-${CIRCLE_SHA1}"
                docker push "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:sha-${CIRCLE_SHA1}"
                docker tag "${CIRCLE_PROJECT_REPONAME}" "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:build-${CIRCLE_BUILD_NUM}"
                docker push "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:sha-${CIRCLE_SHA1}"
                docker push "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest"
              else
                echo "Not pushing: no DOCKER_USER and DOCKER_PASS variables."
              fi
            else
              echo "Not pushing: branch '${CIRCLE_BRANCH}' is not '${only_on_branch}'."
            fi
